tg-bot:
  token: 6231439207:AAFNcJUDPziOUe1fAqAxY2HZ5U7DHvkR634

chain:
  chain_id: "one"
  base_url: "localhost:9090"
  keyring_type: "memory"
  gas_limit: 200000

http:
  port: 3005

redis:
  addr: "localhost:6379"
  password: ""
  db: 0

rabbit:
  url_rabbit: "amqp://guest:guest@localhost:5672/"

extra:
  car_payment_address: cosmos1ttag5890ak34mpw5ptm24g62qex20e5z3gngvz
  url_get_all_cars: http://localhost:3000/v1/user-service/cars/%s
  url_get_user_cars: http://localhost:3000/v1/user-service/user-cars
  url_buy_car: http://localhost:3000/v1/user-service/buy-car/:tx_hash/:car_id
  url_sell_car: http://localhost:3000/v1/user-service/sell-car/:chat_id/:car_id