tg-bot:
  token: 6231439207:AAFNcJUDPziOUe1fAqAxY2HZ5U7DHvkR634

chain:
  chain_id: "one"
  base_url: "0.0.0.0:9090"
  keyring_type: "memory"
  gas_limit: 200000

http:
  port: 3005

redis:
  addr: "localhost:6379"
  password: ""
  db: 0

rabbit:
  url-rabbit: "amqp://guest:guest@localhost:5672/"

minio:
  endpoint: localhost:9000
  user: minio-root-user
  password: minio-root-password
  bucket: car-images

etcd:
  conn-string: "localhost:2379"

extra:
  car-payment-address: cosmos1ttag5890ak34mpw5ptm24g62qex20e5z3gngvz
  url-get-all-cars: http://localhost:3000/v1/user-service/cars
  url-get-user-cars: http://localhost:3000/v1/user-service/user-cars
  url-buy-car: http://localhost:3000/v1/user-service/buy-car/:tx_hash/:car_id
  url-sell-car: http://localhost:3000/v1/user-service/sell-car/:chat_id/:car_id